# Generated by Django 4.1.5 on 2023-01-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=72, unique=True, verbose_name='Категории'),
        ),
    ]
