# Generated by Django 4.1.5 on 2023-02-03 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.author')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='authors',
            field=models.ManyToManyField(through='news.SubscriberAuthor', to='news.author'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='categories',
            field=models.ManyToManyField(through='news.SubscriberCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Имя'),
        ),
    ]
